modLoader = "javafml"
loaderVersion = "[5,)"
license = "All Rights Reserved"

[[mods]]
modId = "ai_gui_mspgrm71"
version = "1.0.0"
displayName = "AI Gui Mod"
description = '''Salut enfaite je voudrais faire un mods Minecraft en 1.16.5 qui permettrer avec des gui iencraft classic au joueur avec la commande /ah d'ouvrir un gui basique ou il pourrait vendre leur item en jeu avec un prix un delai de l'article par exemple il reste en vente 5 semaines etc que le joueur puisse joindre un prix mais surtout que quand un autre joueur l'achete les sous parte du compte banquaire du ods EconomyInc.'''

[[dependencies.ai_gui_mspgrm71]]
modId = "forge"
mandatory = true
versionRange = "[36.2.39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ai_gui_mspgrm71]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"
