modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/Pumko16875k/auction/issues"

[[mods]]
modId="auctionhouse"
version="1.0.0"
displayName="Auction House"
logoFile=""
credits=""
authors="Pumko"
description="Mod d'Hôtel de Ventes"
license="MIT"

[[dependencies.auctionhouse]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.auctionhouse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
